{{ if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
  labels: {{ include "common.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.secrets.ssh }}
  {{ $val.name }}_public: {{ $val.public | printf "%s\n" | b64enc }}
  {{ $val.name }}_private: {{ $val.private | printf "%s\n" | b64enc }}
{{- end }}
{{- range $key, $val := .Values.secrets.ca }}
  ca_{{ $val.name }}_public: {{ $val.public | b64enc }}
{{- end }}
{{ end }}
