apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.ingress.containerPort }}
    targetPort: http
    protocol: TCP
  - name: websocket
    port: {{ .Values.ingress.websocketPort }}
    targetPort: websocket
    protocol: TCP
  selector: {{ include "common.selectorLabels" . | nindent 4 }}
