image:
  repository: docker.io/2igs/ibexcode
  tag:

ingress:
  containerPort: 8080
  enable: false
  host:
  tls:

storage:
  enable: false
  # hostPath:


secrets:
  config: |-
    bind-addr: 0.0.0.0:80
    auth: none
  # gitconfig: |-
  #   [user]
  #     name = user
  #     email = "user@example.com"
  # ssh:
  # - name:
  #   public:
  #   private:
  # ca:
  # - name: self
  #   public:
