image:
  repository: docker.io/2igs/ibexcode
  tag:

# secrets:
#   ssh:
#   - name:
#     public:
#     private:
#   ca:
#   - name:
#     public:

ingress:
  enable: false
  host:
  tls:

storage:
  enable: false
  # hostPath:

# gitconfig: |-
#   [user]
#     name = ""
#     email = ""
