image:
  repository: docker.io/2igs/ibexcode
  tag:

ingress:
  enable: false
  host:
  tls:

storage:
  enable: false
  # hostPath:

# You can put env variabes bellow
config:

# Secrets to be mounted on the pod
secrets:
  config: |-
    bind-addr: 0.0.0.0:8080
    auth: none
  podmanConfig: |+
    [containers]
    netns="host"
    userns="host"
    ipcns="host"
    utsns="host"
    cgroupns="host"
    cgroups="disabled"
    log_driver = "k8s-file"
    default_sysctls = [] # Workaround
    [engine]
    cgroup_manager = "cgroupfs"
    events_logger="file"
    runtime="crun"
  # gitconfig: |-
  #   [user]
  #     name = user
  #     email = "user@example.com"
  # ssh:
  # - name:
  #   public:
  #   private:
  # ca:
  # - name: self
  #   public:
